<#
.SYNOPSIS
    AgentX Context Capture Script (PowerShell)

.DESCRIPTION
    Captures session context for handoffs between agents.
    Creates context summary file and optionally posts to GitHub issue.

.PARAMETER Role
    The agent role: pm, ux, architect, engineer, reviewer, devops

.PARAMETER IssueNumber
    The GitHub issue number

.EXAMPLE
    .\capture-context.ps1 -Role pm -IssueNumber 123
#>

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("pm", "ux", "architect", "engineer", "reviewer", "devops")]
    [string]$Role,

    [Parameter(Mandatory=$true)]
    [int]$IssueNumber
)

$ErrorActionPreference = "Stop"

# Output file paths
$ContextFile = "docs/progress/ISSUE-$IssueNumber-context.md"
$ProgressFile = "docs/progress/ISSUE-$IssueNumber-log.md"

Write-Host ""
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "  AgentX Context Capture" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "Role: $Role" -ForegroundColor Green
Write-Host "Issue: #$IssueNumber" -ForegroundColor Green
Write-Host ""

# Ensure progress directory exists
if (-not (Test-Path "docs/progress")) {
    New-Item -ItemType Directory -Path "docs/progress" -Force | Out-Null
}

# Capture git information
try {
    $Branch = git branch --show-current 2>$null
    if (-not $Branch) { $Branch = "unknown" }
} catch { $Branch = "unknown" }

try {
    $LastCommit = git log -1 --pretty=format:"%h - %s (%cr)" 2>$null
    if (-not $LastCommit) { $LastCommit = "none" }
} catch { $LastCommit = "none" }

try {
    $ChangedFiles = git diff --name-only HEAD~1 2>$null | Select-Object -First 20
    if (-not $ChangedFiles) { $ChangedFiles = @("none") }
} catch { $ChangedFiles = @("none") }

# Role-specific artifact mapping
$ArtifactMap = @{
    "pm" = @{
        Artifacts = @("docs/prd/PRD-$IssueNumber.md")
        Type = "PRD"
        NextAgent = "UX Designer or Architect"
    }
    "ux" = @{
        Artifacts = @("docs/ux/UX-$IssueNumber.md")
        Type = "UX Design"
        NextAgent = "Architect"
    }
    "architect" = @{
        Artifacts = @("docs/adr/ADR-$IssueNumber.md", "docs/specs/SPEC-$IssueNumber.md")
        Type = "ADR + Technical Spec"
        NextAgent = "Engineer"
    }
    "engineer" = @{
        Artifacts = @("src/**", "tests/**")
        Type = "Implementation + Tests"
        NextAgent = "Reviewer"
    }
    "reviewer" = @{
        Artifacts = @("docs/reviews/REVIEW-$IssueNumber.md")
        Type = "Code Review"
        NextAgent = "Done or Engineer (if changes needed)"
    }
    "devops" = @{
        Artifacts = @(".github/workflows/**", "docs/deployment/**")
        Type = "Pipeline + Deployment Docs"
        NextAgent = "Reviewer"
    }
}

$RoleConfig = $ArtifactMap[$Role]

# Check for artifacts
Write-Host "Checking artifacts..." -ForegroundColor Yellow
$ArtifactsFound = @()
foreach ($artifact in $RoleConfig.Artifacts) {
    if ($artifact -like "*`*`*") {
        # Wildcard pattern
        $matches = Get-ChildItem -Path $artifact -ErrorAction SilentlyContinue
        if ($matches) {
            $ArtifactsFound += "- $artifact ($(($matches | Measure-Object).Count) files)"
            Write-Host "  Found: $artifact" -ForegroundColor Green
        } else {
            Write-Host "  Missing: $artifact" -ForegroundColor Yellow
        }
    } else {
        if (Test-Path $artifact) {
            $ArtifactsFound += "- $artifact"
            Write-Host "  Found: $artifact" -ForegroundColor Green
        } else {
            Write-Host "  Missing: $artifact" -ForegroundColor Yellow
        }
    }
}

# Generate context summary
Write-Host ""
Write-Host "Generating context summary..." -ForegroundColor Cyan

$Timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss") + " UTC"
$RoleTitle = (Get-Culture).TextInfo.ToTitleCase($Role)

$ContextContent = @"
# Context Capture: Issue #$IssueNumber

**Captured**: $Timestamp
**Role**: $Role
**Branch**: $Branch

## Handoff Summary

**From**: $RoleTitle Agent
**To**: $($RoleConfig.NextAgent)
**Artifact Type**: $($RoleConfig.Type)

## Artifacts Created
$($ArtifactsFound -join "`n")

## Recent Changes

**Last Commit**: $LastCommit

**Changed Files**:
``````
$($ChangedFiles -join "`n")
``````

## Session State

- **Status**: Ready for handoff
- **Validation**: Run ``./validate-handoff.sh $IssueNumber $Role`` to verify

## Notes for Next Agent

<!-- Add any important context for the next agent -->
- Review the artifacts listed above
- Check the progress log at ``$ProgressFile``
- Verify all acceptance criteria are met

---
*Generated by AgentX capture-context.ps1*
"@

$ContextContent | Set-Content -Path $ContextFile -Encoding UTF8
Write-Host "Context captured to: $ContextFile" -ForegroundColor Green

# Update progress log if it exists
if (Test-Path $ProgressFile) {
    $ProgressUpdate = @"

## Handoff Captured - $Timestamp

- **Role**: $Role
- **Next**: $($RoleConfig.NextAgent)
- **Context**: See ``$ContextFile``
"@
    Add-Content -Path $ProgressFile -Value $ProgressUpdate
    Write-Host "Progress log updated: $ProgressFile" -ForegroundColor Green
}

# Post to GitHub issue if gh CLI available
if (Get-Command gh -ErrorAction SilentlyContinue) {
    Write-Host ""
    Write-Host "Posting context to GitHub issue..." -ForegroundColor Yellow

    $CommentBody = @"
## Context Captured - $RoleTitle Agent

**Timestamp**: $Timestamp
**Branch**: ``$Branch``
**Last Commit**: ``$LastCommit``

**Artifacts Ready**:
$($ArtifactsFound -join "`n")

**Next Agent**: $($RoleConfig.NextAgent)

---
*Run ``./validate-handoff.sh $IssueNumber $Role`` to validate before status change.*
"@

    try {
        gh issue comment $IssueNumber --body $CommentBody 2>$null
        Write-Host "Posted to GitHub issue #$IssueNumber" -ForegroundColor Green
    } catch {
        Write-Host "Could not post to GitHub (check authentication)" -ForegroundColor Yellow
    }
} else {
    Write-Host "GitHub CLI not available - skipping issue comment" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "=========================================" -ForegroundColor Green
Write-Host "  Context capture complete!" -ForegroundColor Green
Write-Host "=========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Run: ./validate-handoff.sh $IssueNumber $Role"
Write-Host "  2. Update Status to 'Ready' in GitHub Projects"
Write-Host "  3. Next agent ($($RoleConfig.NextAgent)) will continue"
Write-Host ""
