// Feature Controller Implementation
// Generated by AgentX Engineer Agent
// Issue: #50, #51

using Microsoft.AspNetCore.Mvc;

namespace AgentX.Sample.Controllers;

/// <summary>
/// API Controller for Feature management.
/// Implements CRUD operations per SPEC-50.
/// </summary>
[ApiController]
[Route("api/[controller]")]
public class FeaturesController : ControllerBase
{
    private readonly IFeatureService _featureService;
    private readonly ILogger<FeaturesController> _logger;

    public FeaturesController(IFeatureService featureService, ILogger<FeaturesController> logger)
    {
        _featureService = featureService;
        _logger = logger;
    }

    /// <summary>
    /// Get all features with optional filtering.
    /// </summary>
    [HttpGet]
    [ProducesResponseType(typeof(IEnumerable<Feature>), StatusCodes.Status200OK)]
    public async Task<ActionResult<IEnumerable<Feature>>> GetAll([FromQuery] int page = 1, [FromQuery] int pageSize = 20)
    {
        _logger.LogInformation("Getting all features, page {Page}, size {PageSize}", page, pageSize);
        var features = await _featureService.GetAllAsync(page, pageSize);
        return Ok(features);
    }

    /// <summary>
    /// Get a single feature by ID.
    /// </summary>
    [HttpGet("{id:int}")]
    [ProducesResponseType(typeof(Feature), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<Feature>> GetById(int id)
    {
        var feature = await _featureService.GetByIdAsync(id);
        if (feature is null)
        {
            _logger.LogWarning("Feature {Id} not found", id);
            return NotFound();
        }
        return Ok(feature);
    }

    /// <summary>
    /// Create a new feature.
    /// </summary>
    [HttpPost]
    [ProducesResponseType(typeof(Feature), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<Feature>> Create([FromBody] CreateFeatureDto dto)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        var feature = await _featureService.CreateAsync(dto);
        _logger.LogInformation("Created feature {Id}: {Name}", feature.Id, feature.Name);
        return CreatedAtAction(nameof(GetById), new { id = feature.Id }, feature);
    }

    /// <summary>
    /// Update an existing feature.
    /// </summary>
    [HttpPut("{id:int}")]
    [ProducesResponseType(typeof(Feature), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<Feature>> Update(int id, [FromBody] UpdateFeatureDto dto)
    {
        var feature = await _featureService.UpdateAsync(id, dto);
        if (feature is null)
        {
            return NotFound();
        }
        _logger.LogInformation("Updated feature {Id}", id);
        return Ok(feature);
    }

    /// <summary>
    /// Delete a feature.
    /// </summary>
    [HttpDelete("{id:int}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Delete(int id)
    {
        var deleted = await _featureService.DeleteAsync(id);
        if (!deleted)
        {
            return NotFound();
        }
        _logger.LogInformation("Deleted feature {Id}", id);
        return NoContent();
    }
}

// Models
public class Feature
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public FeatureStatus Status { get; set; } = FeatureStatus.Draft;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }
}

public enum FeatureStatus
{
    Draft,
    Active,
    Completed,
    Archived
}

public record CreateFeatureDto(string Name, string Description);
public record UpdateFeatureDto(string? Name, string? Description, FeatureStatus? Status);

// Service Interface
public interface IFeatureService
{
    Task<IEnumerable<Feature>> GetAllAsync(int page = 1, int pageSize = 20);
    Task<Feature?> GetByIdAsync(int id);
    Task<Feature> CreateAsync(CreateFeatureDto dto);
    Task<Feature?> UpdateAsync(int id, UpdateFeatureDto dto);
    Task<bool> DeleteAsync(int id);
}
