// <auto-generated />
using System;
using IdeaManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdeaManagement.Data.Migrations
{
    [DbContext(typeof(IdeaDbContext))]
    [Migration("20260126195121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdeaManagement.Models.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ImpactMetrics")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("impact_metrics");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("ReviewerNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reviewer_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("submitted_by");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("SubmittedDate");

                    b.ToTable("ideas", (string)null);
                });

            modelBuilder.Entity("IdeaManagement.Models.Idea", b =>
                {
                    b.OwnsOne("IdeaManagement.Models.BusinessCase", "BusinessCase", b1 =>
                        {
                            b1.Property<int>("IdeaId")
                                .HasColumnType("integer");

                            b1.Property<int>("EstimatedEffortHours")
                                .HasColumnType("integer")
                                .HasColumnName("estimated_effort_hours");

                            b1.Property<decimal>("EstimatedROI")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("estimated_roi");

                            b1.Property<string>("RiskLevel")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("risk_level");

                            b1.HasKey("IdeaId");

                            b1.ToTable("ideas");

                            b1.WithOwner()
                                .HasForeignKey("IdeaId");
                        });

                    b.Navigation("BusinessCase");
                });
#pragma warning restore 612, 618
        }
    }
}
