// Feature Controller Tests
// Generated by AgentX Engineer Agent
// Issue: #50, #51

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Moq;
using Xunit;

namespace AgentX.Sample.Tests;

/// <summary>
/// Unit tests for FeaturesController.
/// Coverage target: 80%+ per Skills.md
/// </summary>
public class FeaturesControllerTests
{
    private readonly Mock<IFeatureService> _mockService;
    private readonly Mock<ILogger<FeaturesController>> _mockLogger;
    private readonly FeaturesController _controller;

    public FeaturesControllerTests()
    {
        _mockService = new Mock<IFeatureService>();
        _mockLogger = new Mock<ILogger<FeaturesController>>();
        _controller = new FeaturesController(_mockService.Object, _mockLogger.Object);
    }

    #region GetAll Tests

    [Fact]
    public async Task GetAll_ReturnsOkWithFeatures()
    {
        // Arrange
        var features = new List<Feature>
        {
            new() { Id = 1, Name = "Feature 1" },
            new() { Id = 2, Name = "Feature 2" }
        };
        _mockService.Setup(s => s.GetAllAsync(1, 20))
            .ReturnsAsync(features);

        // Act
        var result = await _controller.GetAll();

        // Assert
        var okResult = Assert.IsType<OkObjectResult>(result.Result);
        var returnedFeatures = Assert.IsAssignableFrom<IEnumerable<Feature>>(okResult.Value);
        Assert.Equal(2, returnedFeatures.Count());
    }

    [Fact]
    public async Task GetAll_WithPagination_ReturnsCorrectPage()
    {
        // Arrange
        var features = new List<Feature> { new() { Id = 3, Name = "Feature 3" } };
        _mockService.Setup(s => s.GetAllAsync(2, 10))
            .ReturnsAsync(features);

        // Act
        var result = await _controller.GetAll(page: 2, pageSize: 10);

        // Assert
        var okResult = Assert.IsType<OkObjectResult>(result.Result);
        Assert.NotNull(okResult.Value);
    }

    #endregion

    #region GetById Tests

    [Fact]
    public async Task GetById_ExistingId_ReturnsOkWithFeature()
    {
        // Arrange
        var feature = new Feature { Id = 1, Name = "Test Feature" };
        _mockService.Setup(s => s.GetByIdAsync(1))
            .ReturnsAsync(feature);

        // Act
        var result = await _controller.GetById(1);

        // Assert
        var okResult = Assert.IsType<OkObjectResult>(result.Result);
        var returnedFeature = Assert.IsType<Feature>(okResult.Value);
        Assert.Equal(1, returnedFeature.Id);
    }

    [Fact]
    public async Task GetById_NonExistingId_ReturnsNotFound()
    {
        // Arrange
        _mockService.Setup(s => s.GetByIdAsync(999))
            .ReturnsAsync((Feature?)null);

        // Act
        var result = await _controller.GetById(999);

        // Assert
        Assert.IsType<NotFoundResult>(result.Result);
    }

    #endregion

    #region Create Tests

    [Fact]
    public async Task Create_ValidDto_ReturnsCreatedWithFeature()
    {
        // Arrange
        var dto = new CreateFeatureDto("New Feature", "Description");
        var created = new Feature { Id = 1, Name = dto.Name, Description = dto.Description };
        _mockService.Setup(s => s.CreateAsync(dto))
            .ReturnsAsync(created);

        // Act
        var result = await _controller.Create(dto);

        // Assert
        var createdResult = Assert.IsType<CreatedAtActionResult>(result.Result);
        Assert.Equal(nameof(FeaturesController.GetById), createdResult.ActionName);
        var returnedFeature = Assert.IsType<Feature>(createdResult.Value);
        Assert.Equal("New Feature", returnedFeature.Name);
    }

    #endregion

    #region Update Tests

    [Fact]
    public async Task Update_ExistingId_ReturnsOkWithUpdatedFeature()
    {
        // Arrange
        var dto = new UpdateFeatureDto("Updated", null, FeatureStatus.Active);
        var updated = new Feature { Id = 1, Name = "Updated", Status = FeatureStatus.Active };
        _mockService.Setup(s => s.UpdateAsync(1, dto))
            .ReturnsAsync(updated);

        // Act
        var result = await _controller.Update(1, dto);

        // Assert
        var okResult = Assert.IsType<OkObjectResult>(result.Result);
        var returnedFeature = Assert.IsType<Feature>(okResult.Value);
        Assert.Equal("Updated", returnedFeature.Name);
        Assert.Equal(FeatureStatus.Active, returnedFeature.Status);
    }

    [Fact]
    public async Task Update_NonExistingId_ReturnsNotFound()
    {
        // Arrange
        var dto = new UpdateFeatureDto("Test", null, null);
        _mockService.Setup(s => s.UpdateAsync(999, dto))
            .ReturnsAsync((Feature?)null);

        // Act
        var result = await _controller.Update(999, dto);

        // Assert
        Assert.IsType<NotFoundResult>(result.Result);
    }

    #endregion

    #region Delete Tests

    [Fact]
    public async Task Delete_ExistingId_ReturnsNoContent()
    {
        // Arrange
        _mockService.Setup(s => s.DeleteAsync(1))
            .ReturnsAsync(true);

        // Act
        var result = await _controller.Delete(1);

        // Assert
        Assert.IsType<NoContentResult>(result);
    }

    [Fact]
    public async Task Delete_NonExistingId_ReturnsNotFound()
    {
        // Arrange
        _mockService.Setup(s => s.DeleteAsync(999))
            .ReturnsAsync(false);

        // Act
        var result = await _controller.Delete(999);

        // Assert
        Assert.IsType<NotFoundResult>(result);
    }

    #endregion
}
