name: 'Update GitHub Projects Status'
description: 'Updates the Status field in GitHub Projects v2 for an issue'
inputs:
  issue_number:
    description: 'Issue number to update'
    required: true
  status:
    description: 'Status value (Backlog, Ready, In Progress, In Review, Done)'
    required: true
  github_token:
    description: 'GitHub token with project scope'
    required: true
  project_number:
    description: 'GitHub Project number (defaults to 1)'
    required: false
    default: '1'

runs:
  using: 'composite'
  steps:
    - name: Update Project Status via GraphQL
      uses: actions/github-script@v7
      env:
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        STATUS_VALUE: ${{ inputs.status }}
        PROJECT_NUMBER: ${{ inputs.project_number }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const issueNumber = parseInt(process.env.ISSUE_NUMBER);
          const statusValue = process.env.STATUS_VALUE;
          const projectNumber = parseInt(process.env.PROJECT_NUMBER);
          
          console.log(`🔄 Updating issue #${issueNumber} status to: ${statusValue}`);
          
          try {
            // Step 1: Get issue node_id
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            
            const issueNodeId = issue.node_id;
            console.log(`✅ Found issue node_id: ${issueNodeId}`);
            
            // Step 2: Get project ID and status field ID
            const projectQuery = `
              query($owner: String!, $number: Int!) {
                organization(login: $owner) {
                  projectV2(number: $number) {
                    id
                    field(name: "Status") {
                      ... on ProjectV2SingleSelectField {
                        id
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            let projectData;
            try {
              // Try organization first
              projectData = await github.graphql(projectQuery, {
                owner: context.repo.owner,
                number: projectNumber
              });
            } catch (orgError) {
              console.log('Not an organization project, trying user project...');
              
              // Fallback to user project
              const userProjectQuery = `
                query($owner: String!, $number: Int!) {
                  user(login: $owner) {
                    projectV2(number: $number) {
                      id
                      field(name: "Status") {
                        ... on ProjectV2SingleSelectField {
                          id
                          options {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              projectData = await github.graphql(userProjectQuery, {
                owner: context.repo.owner,
                number: projectNumber
              });
              
              // Adjust the path for user projects
              if (projectData.user) {
                projectData.organization = projectData.user;
              }
            }
            
            const project = projectData.organization.projectV2;
            if (!project) {
              throw new Error(`Project #${projectNumber} not found`);
            }
            
            const projectId = project.id;
            const statusField = project.field;
            
            if (!statusField) {
              throw new Error('Status field not found in project');
            }
            
            const statusFieldId = statusField.id;
            const statusOption = statusField.options.find(opt => opt.name === statusValue);
            
            if (!statusOption) {
              const availableStatuses = statusField.options.map(o => o.name).join(', ');
              throw new Error(`Status '${statusValue}' not found. Available: ${availableStatuses}`);
            }
            
            const statusOptionId = statusOption.id;
            console.log(`✅ Found project ID: ${projectId}`);
            console.log(`✅ Found status field ID: ${statusFieldId}`);
            console.log(`✅ Found status option ID for '${statusValue}': ${statusOptionId}`);
            
            // Step 3: Get project item ID for this issue
            const itemQuery = `
              query($projectId: ID!, $issueNodeId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    items(first: 100) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            id
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            const itemData = await github.graphql(itemQuery, {
              projectId: projectId,
              issueNodeId: issueNodeId
            });
            
            const projectItem = itemData.node.items.nodes.find(
              item => item.content?.id === issueNodeId
            );
            
            if (!projectItem) {
              console.log(`⚠️ Issue #${issueNumber} not found in project #${projectNumber}`);
              console.log('Attempting to add issue to project...');
              
              // Add issue to project first
              const addItemMutation = `
                mutation($projectId: ID!, $contentId: ID!) {
                  addProjectV2ItemById(input: {
                    projectId: $projectId
                    contentId: $contentId
                  }) {
                    item {
                      id
                    }
                  }
                }
              `;
              
              const addResult = await github.graphql(addItemMutation, {
                projectId: projectId,
                contentId: issueNodeId
              });
              
              const newItemId = addResult.addProjectV2ItemById.item.id;
              console.log(`✅ Added issue to project, item ID: ${newItemId}`);
              
              // Now update the status
              const updateMutation = `
                mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: $projectId
                    itemId: $itemId
                    fieldId: $fieldId
                    value: { singleSelectOptionId: $optionId }
                  }) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `;
              
              await github.graphql(updateMutation, {
                projectId: projectId,
                itemId: newItemId,
                fieldId: statusFieldId,
                optionId: statusOptionId
              });
              
              console.log(`✅ Updated status to '${statusValue}' for issue #${issueNumber}`);
              return;
            }
            
            const projectItemId = projectItem.id;
            console.log(`✅ Found project item ID: ${projectItemId}`);
            
            // Step 4: Update the status field
            const updateMutation = `
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId
                  itemId: $itemId
                  fieldId: $fieldId
                  value: { singleSelectOptionId: $optionId }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `;
            
            await github.graphql(updateMutation, {
              projectId: projectId,
              itemId: projectItemId,
              fieldId: statusFieldId,
              optionId: statusOptionId
            });
            
            console.log(`✅ Successfully updated status to '${statusValue}' for issue #${issueNumber}`);
            
          } catch (error) {
            console.error(`❌ Failed to update project status: ${error.message}`);
            console.error('Full error:', error);
            // Don't fail the workflow, just log the error
            core.warning(`Could not update project status: ${error.message}`);
          }
